Add tags for Docker images
Analog-Labs/chain-connectors pull request #146
Opened 2023-07-27 09:32 UTC by penumbra23

## Description

Extends the Docker scripts to push tagged images. 

The CI trigger has been changed to `push: master`, so on each new push/PR merged, the CI builds and pushes the latest image together with the 8-char commit hash.

## Code review prechecks:

- [x] Code follows the style guidelines of this project
- [x] Code has been self-reviewed
- [x] Inline comments have been added for each method
- [ ] I have made corresponding changes to the documentation
- [x] Code changes introduces no new problems or warnings
- [ ] Test cases have been added
- [ ] Dependent changes have been merged and published in downstream modules

2023-07-27 17:11 UTC, dvc94ch approved these changes

2023-07-27 17:11 UTC, dvc94ch commented
thanks bran!

2023-07-27 21:48 UTC, Lohann requested changes
Unit tests are failling with `error: Connection reset by peer` and `error: connection closed`, which is not suppose to happen.

On #140 I also made changes on `build_connectors.sh` and for some reason it broke CI too, seems the same is happening here, I'm still investigating why it is happening. Update this branch with latest master where are all tests are working fine, just to make sure.

2023-07-28 05:56 UTC, Lohann approved these changes
Ok solved the issue on #140, when building on linux we should not declare the linker.
PR approved, just need to update with latest master.

2023-07-28 10:22 UTC, merged