#237 Fix ethereum-based chains testnet public keys
Analog-Labs/chain-connectors pull request #246
Opened 2024-06-25 10:19 UTC by Haider-Ali-DS

## Description

This PR fixes ethereum based chains testnet public keys which are different then what public wallet shows.
It changes coin ids from 1 to 60 for current ethereum based supported testnets by chain-connectors.

Fixes # (issue)
https://github.com/Analog-Labs/chain-connectors/issues/237

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Tests

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:

## Code review prechecks:

- [x] Code follows the style guidelines of this project
- [x] Code has been self-reviewed

2024-06-25 23:53 UTC, Lohann approved these changes

2024-08-28 15:09 UTC, Lohann requested changes
Waiting for @penumbra23 thumps up

2024-09-04 11:17 UTC, dvc94ch approved these changes

2024-09-04 11:17 UTC, merged

2024-09-06 13:48 UTC, FlorianFranzen commented
@Haider-Ali-DS @Lohann Should we "fix" Astar as well, if metamask uses a `60` for them as well? Are there other wallets that use the correct coin identifier?

2024-09-06 13:53 UTC, Lohann commented
The issue is that we also use the BIP44 ID for Astar SS58 address, the issues is that if you import a mneumonic on Metamask, it will derivate the wallet from `60`, if you import it on PolkadotJS extension, it will use a different derivation.